version: '3.8'

services:
  jenkins:
    platform: linux/x86_64
    container_name: jenkins
    build:
      dockerfile: ./jenkins/Dockerfile
      context: .
      args:
        ADMIN_PASSWORD: $JENKINS_ADMIN_PASSWORD
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${JENKINS_PORT}:8080
      - 50000:50000
    networks:
      - local-dev-network

  postgresql:
    platform: linux/x86_64
    container_name: postgresql
    image: postgres:13.5
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${VOLUME_PATH}/postgresql:/var/lib/postgresql/data
    restart: always
    networks:
      - local-dev-network

  jupyter-lab:
    container_name: jupyter-lab
    platform: linux/x86_64
    build:
      context: jupyter-lab/.
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    ports:
      - ${JUPYTERLAB_PORT}:8888
    volumes:
      - ${VOLUME_PATH}/jupyter-lab:/home/ubuntu/sd-local_environment_data
    networks:
      - local-dev-network

networks:
  local-dev-network:
    driver: 'bridge'
